### ISSUE TITLE
Completed tasks

### ISSUE THREAD

**Issue by OrganicChem** [sarajbosna2012/essex#1]
1. Show static and clickable image in bot. ---->>> FIXED.

1. Show hyperlink in bot. ----> FIXED

1. If hyperlink is click, show the bot conversation resumes on the new URL (you can create fake url).---->>> FIXED

1. Be able to email chat history to user (collect their email).  --->> FIXED

**Comment by sarajbosna2012** [comment]
Points 1 and 2.
![image](https://user-images.githubusercontent.com/56974785/67639004-167ffb80-f8eb-11e9-98bc-33986de26c09.png)

**Comment by sarajbosna2012** [comment]
![image](https://user-images.githubusercontent.com/56974785/67639068-bb023d80-f8eb-11e9-819e-56dc053c1a4c.png)

**Comment by sarajbosna2012** [comment]
type get url to get url
![image](https://user-images.githubusercontent.com/56974785/67639153-b4c09100-f8ec-11e9-88ad-b77bc191897a.png)

**Comment by sarajbosna2012** [comment]
issue 3 running across URLs is not possible.

**Comment by sarajbosna2012** [comment]
Email written issue to support. Go to Software Functions, Software bug or other issue. Follow prompts. Email will be sent to admin email set in code.
![image](https://user-images.githubusercontent.com/56974785/67770497-ca51ca00-fa56-11e9-8e30-80247a69a961.png)

**Comment by sarajbosna2012** [comment]
customer demands history of conversation being emailed to their email address....type email at prompt
enter email address. email will be sent. all emails are being sent from my gmail account. this should be changed to your account later.
![image](https://user-images.githubusercontent.com/56974785/67770852-798ea100-fa57-11e9-9341-61d62191b1bb.png)

**Comment by OrganicChem** [comment]
> issue 3 running across URLs is not possible.

Can you explain what you mean here?

**Comment by sarajbosna2012** [comment]
> 
> 
> > issue 3 running across URLs is not possible.
> 
> Can you explain what you mean here?

basically we said we will open links in new windows. I thought issue 3 is related to bot going accross URLS.

**Comment by OrganicChem** [comment]
> > > issue 3 running across URLs is not possible.
> > 
> > 
> > Can you explain what you mean here?
> 
> basically we said we will open links in new windows. I thought issue 3 is related to bot going accross URLS.

No, as we spoke, new window opening is fine. Just as long as the conversation is active, which it is.  Bot moving the user to different URLs may not be very ethical!
